name: Auto-merge
on: pull_request_target

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'akeylimepie'
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge
